default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: name-tests-test

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Formatting with Black (black .)
        args: ["--line-length", "79"]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sorting imports (isort .)
        args: ["--profile", "black", "--line-length=79"]

  - repo: local
    hooks:
      - id: poetry-check
        name: Poetry check pyproject.toml (poetry check)
        entry: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: false

      - id: pytest
        name: Running tests (pytest --cov)
        entry: pytest --cov
        language: system
        files: pyproject.toml
        pass_filenames: false
        stages: [push, manual]

      - id: poetry-update
        name: Poetry update (poetry update)
        entry: poetry update
        language: system
        files: pyproject.toml
        pass_filenames: false
        stages: [push, manual]

      - id: poetry-lock
        name: Poetry lock (poetry lock)
        entry: poetry lock
        language: system
        files: pyproject.toml
        pass_filenames: false
        stages: [push,  manual]
